"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@heroui/react";
import { useMemoryDocumentQuery } from "@/lib/hooks/use-memory-document-query";
import { EditMemoryDocumentModal } from "./edit-memory-document-modal";
import { DeleteMemoryDocumentModal } from "./delete-memory-document-modal";

interface MemoryDocumentDetailClientProps {
    orgId: string;
    memoryId: string;
    documentId: string;
}

function formatDate(d: Date): string {
    return new Intl.DateTimeFormat("en", {
        dateStyle: "medium",
        timeStyle: "short",
    }).format(new Date(d));
}

export function MemoryDocumentDetailClient({
    orgId,
    memoryId,
    documentId,
}: Readonly<MemoryDocumentDetailClientProps>) {
    const { data: document, isLoading } = useMemoryDocumentQuery(
        memoryId,
        documentId,
    );
    const [editOpen, setEditOpen] = useState(false);
    const [deleteOpen, setDeleteOpen] = useState(false);

    if (isLoading || !document) {
        return (
            <div className="animate-pulse flex flex-col gap-4">
                <div className="h-6 w-48 bg-foreground/10 rounded" />
                <div className="h-4 w-32 bg-foreground/10 rounded" />
                <div className="h-64 bg-foreground/10 rounded-lg" />
            </div>
        );
    }

    return (
        <div className="flex flex-col gap-6">
            <div>
                <Link
                    href={`/memories/${memoryId}`}
                    className="text-sm text-foreground/50 hover:text-foreground transition-colors"
                >
                    ← Back to Memory
                </Link>
            </div>

            {document.isCondensationSummary && (
                <div className="rounded-lg border border-purple-500/20 bg-purple-500/5 px-4 py-3">
                    <p className="text-sm font-medium text-purple-400">
                        AI-Generated Summary
                    </p>
                    <p className="text-xs text-foreground/60 mt-1">
                        This content was automatically generated by condensing older
                        documents. It may not capture every detail from the original
                        sources.
                    </p>
                </div>
            )}

            <div className="flex items-start justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold">{document.title}</h1>
                    <div className="flex gap-4 mt-2 text-xs text-foreground/50">
                        <span>Created {formatDate(document.createdAt)}</span>
                        <span>Modified {formatDate(document.updatedAt)}</span>
                    </div>
                </div>
                <div className="flex gap-2 shrink-0">
                    <Button
                        size="sm"
                        variant="outline"
                        onPress={() => setEditOpen(true)}
                    >
                        Edit
                    </Button>
                    <Button
                        size="sm"
                        variant="danger"
                        onPress={() => setDeleteOpen(true)}
                    >
                        Delete
                    </Button>
                </div>
            </div>

            <div className="rounded-lg border border-foreground/10 bg-surface p-6">
                <pre className="whitespace-pre-wrap text-sm text-foreground/80 font-sans leading-relaxed">
                    {document.content || "(No content)"}
                </pre>
            </div>

            {editOpen && (
                <EditMemoryDocumentModal
                    memoryId={memoryId}
                    document={document}
                    onClose={() => setEditOpen(false)}
                />
            )}

            {deleteOpen && (
                <DeleteMemoryDocumentModal
                    memoryId={memoryId}
                    document={document}
                    onClose={() => setDeleteOpen(false)}
                />
            )}
        </div>
    );
}
